     name: Atualizar JSON de Vagas

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Instalar dependências
        run: pip install requests

      - name: Baixar e processar o feed
        run: python script.py 
      - name: Listar arquivos gerados
        run: ls -lah
  
      - name: Commit e Push das mudanças
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add vagas.json
          git commit -m "Atualização automática do JSON" || exit 0
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Dulcimar-Vieira/vagas-json.git main
